### PR TITLE
fix(analytics): improve alias save

### PR DESCRIPTION
**Pull request by Yelinz**
## Description
use different icon as a checkmark is confusing

image
this looks like it has been auto saved, just like in the form
image
looks more something you have to click than before

as uikit doesnt have a classical save icon, which would be better, this just uses something similar
I'm open to suggestions to use a different icon

### CODE REVIEW

**Comment by anehx** [comment]
Have you tried `download`. I think this one will confuse as well.. ^^

**Comment by anehx** [comment]
I just discussed this with @kaldras, why aren't we autosaving? Also, a button in an input field is somehow not really intuitive, why don't we just put a save button next to it?

**Comment by Yelinz** [comment]
Not sure, changed to auto save, to be consistent with the other fields

**Review by anehx — APPROVED** [review]
LGTM :+1:

**Pull request merged**
