### PR TITLE
Fix test suite

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Review by velrest — APPROVED** [review]

**Comment by Yelinz** [comment]
Seems the failure is caused by ember-gestures, which is used by ember-toggle, which comes from ember-uikit. Their teardown function doesnt seem to be compatible with ember 3.22

**Comment by czosel** [comment]
Can you open a PR in ember-gestures that fixes this @Yelinz ? cc @anehx

**Comment by Yelinz** [comment]
> Can you open a PR in ember-gestures that fixes this 

https://github.com/emberjs/ember.js/issues/19192

Ive narrowed it down to a problem in ember, it should be a deprecation but it throws an error

**Comment by Yelinz** [comment]
Waiting for a new release in ember then the pipelines will be fixed

**Comment by czosel** [comment]
Should we mark the ember-release stage as optional in order to move forward?

**Comment by Yelinz** [comment]
> Should we mark the ember-release stage as optional in order to move forward?

Imo yes, the test should run but we say latest lts support which is 3.20

**Comment by anehx** [comment]
Temporarily yes, but we always need to support the latest version. Support for latest LTS means back to that version not only that version..

**Review by velrest — APPROVED** [review]

**Pull request merged**
