### PR TITLE
fix(lib/navigation): don't set state to empty if fields are required

### PR DESCRIPTION
**Pull request by fkm-adfinis**
Otherwise, there's no other way than do go though all (sub-)forms
to check where the missing question is located.

### CODE REVIEW

**Comment by fkm-adfinis** [comment]
Screenshot_20210210_121942

The question marks show where there are missing questions. The orange color shows that they are dirty.

**Review by anehx — CHANGES_REQUESTED** [review]
That doesn't make any sense to me.. Why are we excluding empty optional field? This would mean that when the user only fills an optional field the state in the navigation would still show empty - which is wrong.

**Comment by fkm-adfinis** [comment]
We are excluding non-optional fields to help the user find forms with missing fields that are required.

The `empty`/`in-progress` might be used incorrectly here. But I'm open to suggestions. What I need is for the navigation to show which form is missing input. Even if the form has never been touched.

**Comment by anehx** [comment]
LGTM, if you think you tested it and it does what it should you can go ahead and merge.

**Review by anehx — APPROVED** [review]

**Comment by anehx** [comment]
Ah, commit message now doesn't fit the changes anymore - please fix that before merging..

**Pull request merged**
