### PR TITLE
fix(deps): upgrade to babel 7

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
This still need to be tested with a consuming app, and the according release notes have to be added (I'm expecting this to be a breaking change)

**Comment by fkm** [comment]
Breaking because of the Ember CLI update?

**Comment by czosel** [comment]
I expect this to be breaking because probably we'll have to upgrade the babel config in consuming apps as well.

**Comment by fkm** [comment]
Ok

**Comment by czosel** [comment]
Just tested it, and it turns out that this isn't breaking at all! :+1:

**Pull request merged**
