### PR TITLE
fix(translations): change "optional" to "optionnelle"

### PR DESCRIPTION
**Pull request by StephanH90**
## Description

Changes "optional" in French to "optionnelle". That is, according to one of our French speaking clients, the correct translation.

### CODE REVIEW

**Comment by amchangama** [comment]
**optionnelle** is the feminine, using **optionnel** (masculin) is common if we are not sure of what were refering to(either feminine or masculine)

**Comment by anehx** [comment]
> **optionnelle** is the feminine, using **optionnel** (masculin) is common if we are not sure of what were refering to(either feminine or masculine)

In this case "optional" refers to the question which is a feminine word: https://dictionnaire.lerobert.com/definition/question

So IMO this change is correct, right @amchangama ?

**Comment by amchangama** [comment]
@anehx  yes it is correct if it refers to a question

**Review by anehx — APPROVED** [review]

**Pull request merged**
