### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by anehx**
Closes #583
Closes #574
Closes #573
Closes #571 
Closes #569
Closes #563
Closes #562
Closes #560
Closes #559  
Closes #558
Closes #555
Closes #551
Closes #545

### CODE REVIEW

**Comment by anehx** [comment]
https://github.com/ember-cli/ember-cli-htmlbars/issues/312 This is the reason for the failing build. Will fix as soon as they released a fix..

**Comment by anehx** [comment]
This https://github.com/ember-cli/ember-cli-htmlbars/issues/297 is also blocking

**Comment by rwjblue** [comment]
Updating to ember-cli-htmlbars@4.0.5 should fix the duplicate plugin/preset error.

**Pull request merged**
