### PR TITLE
refactor(slug): use slugify options instead of manual operations

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Review by JohnL17 — APPROVED** [review]

**Review by czosel — APPROVED** [review]
:+1: 

One other thing which is somewhat related that I'd like to improve: Could we replace `ä`, `ö`, `ü` by `ae`, `oe`, `ue`?

**Comment by anehx** [comment]
I think we'd need to pass the locale for that to work: https://github.com/simov/slugify/blob/master/config/locales.json

**Comment by czosel** [comment]
Ah, I didn't know there is locale support. Would be awesome to have this!

**Comment by anehx** [comment]
Done!

**Comment by czosel** [comment]
:100:

**Pull request merged**
