### PR TITLE
Subform navigation

### PR DESCRIPTION
**Pull request by czosel**
Depends on https://github.com/projectcaluma/caluma/pull/349

### CODE REVIEW

**Comment by fkm** [comment]
I get the following error:
> Cannot read property 'fields' of undefined
    at cf-navigation.js:37

The property `field.childDocument` is set but to `undefined`.

**Comment by czosel** [comment]
@fkm would be awesome if you could take another look :slightly_smiling_face:

**Comment by fkm** [comment]
I still get the same error. Here's what I've got in my backend:

```
{
  "data": {
    "allForms": {
      "edges": [
        {
          "node": {
            "slug": "form-2",
            "questions": {
              "edges": [
                {
                  "node": {
                    "slug": "q1",
                    "__typename": "TextQuestion",
                    "forms": {
                      "edges": [
                        {
                          "node": {
                            "slug": "form-2"
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "slug": "form-1",
            "questions": {
              "edges": [
                {
                  "node": {
                    "slug": "f1",
                    "__typename": "FormQuestion",
                    "forms": {
                      "edges": [
                        {
                          "node": {
                            "slug": "form-1"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "node": {
                    "slug": "q2",
                    "__typename": "TextQuestion",
                    "forms": {
                      "edges": [
                        {
                          "node": {
                            "slug": "form-1"
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

Could the problem arise from having the sub form attached to every question? (i.e. q1 and q2)

I managed to have the sub form work at some point. But then I added more stuff and everything broke. I try to find out, which case works.

**Comment by czosel** [comment]
Yeah, having the same subform attached to multiple FormQuestions could definitely be the issue. Can you test with different subforms?

**Comment by fkm** [comment]
Attaching the sub forms to question types other than FormQuestion is not something I did through the UI. Seems to be something GraphQL does in the background. Either on save or fetch.

Here's the query I used to get the previous result:

```
query {
  allForms {
    edges {
      node {
        slug
        questions {
          edges {
            node {
              slug
              forms {
                edges {
                  node {
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by fkm** [comment]
But at the moment it doesn't display anything. The document/form is returned by the backend but the form is missing from the frontend. I'll have a look at the code.

**Pull request merged**
