### PR TITLE
fix(form): update design for input type "file"

### PR DESCRIPTION
**Pull request by aziiee**
This will change the design as follows:

image

### CODE REVIEW

**Review by anehx — CHANGES_REQUESTED** [review]
Tests need to be updated, otherwise LGTM! Looks way better :100: :fire:

**Review by anehx — CHANGES_REQUESTED** [review]
Hm, if I see correctly this will display absolutely nothing if disabled - that's not good..

**Comment by aziiee** [comment]
> Hm, if I see correctly this will display absolutely nothing if disabled - that's not good..

@anehx Right.. fixed it. The input will now be disabled instead.

**Review by anehx — APPROVED** [review]

**Pull request merged**
