### PR TITLE
ADD component overrides and crossreferences

### PR DESCRIPTION
**Pull request by fkm**
* Specify overriding components via slug.
* Reference other questions via slug.

### CODE REVIEW

**Comment by czosel** [comment]
Can you update the documentation for this?

Also, I'm not really happy with `crossReference` - it looks more like a custom functionality instead of something that should go in the addon. Can't you call the fields `save` method without the extra action, just based on the `field` property which is passed into the custom component?

**Comment by fkm** [comment]
I found a way.

**Comment by czosel** [comment]
So you'll open a new PR for the component override part?

**Comment by fkm** [comment]
I've assigned you a pull request in the project repository. The cross-reference part is now done through field.document.fields and doesn't require any change to ember-caluma.

**Comment by czosel** [comment]
Awesome! But you'll need a change here for the override part, right?

**Comment by fkm** [comment]
You're right! My bad!

**Comment by czosel** [comment]
Can you add a short test and some docs for this?

**Comment by czosel** [comment]
Merging for our deployment, created #73 to keep track of the missing parts.

**Pull request merged**
