### PR TITLE
Form builder/renderer: Add placeholder and info text

### LINKED ISSUE #4: Add "Hint" field for questions
The hint would be displayed below the input element and is contains help text for the user. We should consider using a simple markup language (e.g. Markdown) to support things like links inside the help text.

### PR DESCRIPTION
**Pull request by czosel**
Depends on https://github.com/projectcaluma/caluma/pull/379

Fixes #4

### CODE REVIEW

**Comment by fkm** [comment]
Wouldn't a ["drop"](https://getuikit.com/docs/drop) be better suited for this?

**Comment by czosel** [comment]
@fkm Cool, I didn't know about the drop. I went for the modal pretty much straight away because that's what was done in another project already. I'll try the drop, thanks for suggesting :+1:

**Comment by czosel** [comment]
@fkm done!

**Comment by fkm** [comment]
Looks good.

**Pull request merged**
