### PR TITLE
chore(octane): upgrade form builder to glimmer and octane

### PR DESCRIPTION
**Pull request by derrabauke**

### CODE REVIEW

**Comment by derrabauke** [comment]
> untracked files on glimmerify-components: 2a6a982 chore: rewrite to o… 
7c0a707
&&
> index on glimmerify-components: 2a6a982 chore: rewrite to octane comp… 
f58afef

... those where stashed changes which went into the commit history with the stash message instead of a nice commit message. Sorry for that. Further I should have used `rebase` strategy instead of `merge` to get rid of the merge commits. Or is this fine?

**Comment by anehx** [comment]
We'll definitely need to squash this, normally we use rebase.

You have some merge conflicts and the tests are not running, could you fix that?

**Review by anehx — APPROVED** [review]
Awesome work!

**Pull request merged**
