### PR TITLE
fix(document): add fallback if no fields

### PR DESCRIPTION
**Pull request by fkm**
doc.getWithDefault() would be nice here. But I couldn't reproduce the 
error and didn't want to spend too much time on that.

### CODE REVIEW

**Comment by fkm** [comment]
I actually cannot. I had this error after finishing a case. But I didn't catch where exactly that came from and couldn't reproduce it.

**Comment by fkm** [comment]
As - AFAIK - today's test has already started I'll keep this one open and see if I can reproduce the error.

**Comment by anehx** [comment]
@fkm Do you think this is still necessary?

**Comment by fkm** [comment]
Good question. I stumbled upon this yesterday. Probably not.

**Comment by anehx** [comment]
Closed since #376 refactored this bit

**Pull request closed without merging**
