### PR TITLE
Fix caching

### PR DESCRIPTION
**Pull request by fkm**
The network policy property name was incorrect.

### CODE REVIEW

**Comment by fkm** [comment]
Floating dependencies are failing as we are using a private method in our code.  
https://github.com/projectcaluma/ember-caluma/blob/master/addon/utils/jexl.js#L17

@czosel Is our implementation really the correct one? I wonder if it is not possible to use the library without falling back to using 'private' methods.

**Comment by czosel** [comment]
I think @anehx wrote that bit...

**Comment by anehx** [comment]
> Floating dependencies are failing as we are using a private method in our code.
> [/addon/utils/jexl.js@`master`#L17](https://github.com/projectcaluma/ember-caluma/blob/master/addon/utils/jexl.js#L17) [](/projectcaluma/ember-caluma/blob/HEAD@{2019-09-04T06:47:02Z}/addon/utils/jexl.js#L17)
> 
> @czosel Is our implementation really the correct one? I wonder if it is not possible to use the library without falling back to using 'private' methods.

At the time I wrote that bit of code there was no way to parse the AST without using private methods. Is there now?

**Comment by anehx** [comment]
@fkm I think we should change some of the commit types:

`fix(dummy)` => `docs(dummy)` dummy changes are always `docs`
`fix(docker)` => `chore(docker)` this is just a dependency update
`fix(gitignore)` => `chore(gitignore)` this is the perfect example for a chore / cleanup

The way the messages are now, we'd have a lot of irrelevant noise in our changelog. We should avoid that...

**Comment by fkm** [comment]
Ok. I'll change those first thing in the afternoon.

**Comment by anehx** [comment]
@fkm please rebase, #518 resolved the build issue :smile:

**Pull request merged**
