### PR TITLE
fix(testing): mock DateTime scalar

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Review by anehx — CHANGES_REQUESTED** [review]
This will result in every datetime being the current time - we don't want this. Why do you need this?

**Comment by Yelinz** [comment]
Noticed that as well, still working on this. 
The problem is that when using this addon it will throw the error `No mock defined for type "DateTime"`
which led me to monkey patching a DateTime mock there and that resolved the error

**Comment by Yelinz** [comment]
Date and DateTime aren't default graphql scalar types and DateTiime isn't defined in `mirage-graphql/mocks/base.js` which lead me to belive it wasn't being mocked and added it here

**Comment by anehx** [comment]
That means that there is no data on the model. What field on what model did you try to get?

**Comment by Yelinz** [comment]
case createdAt and modifiedAt, which should be generated by the factory when I generate them.

**Comment by Yelinz** [comment]
Overlooked closedAt, closing as its not a bug. Started some updating of graphql-tools, will commit that in a other PR.

**Pull request closed without merging**
