### PR TITLE
Scroll to top on document change

### PR DESCRIPTION
**Pull request by fkm**
Not sure if `finally` is the right place.

The reasoning is that I cannot add it at the end of the `try` block as there are `return`s before that. My problem with `finally` is that it will scroll on error which might be confusing.

### CODE REVIEW

**Comment by czosel** [comment]
Do you know what kind of exceptions we're expecting in that try/catch block?

**Comment by fkm** [comment]
No. As there is no API call I guess it's about the data structure.

**Comment by czosel** [comment]
Might be a good idea to refactor the code with things like `getWithDefault` and similar safety checks?

**Comment by fkm** [comment]
That's a task for someone who actually knows what's going on (data structures and requirements). I didn't even know that this component existed until today.

**Comment by czosel** [comment]
Probably, that would be me :sweat_smile:

**Pull request merged**
