### PR TITLE
fix(distribution): make sure distribution components are prefixed

### PR DESCRIPTION
**Pull request by anehx**
This makes sure that our component names don't collide with the hosts components

### CODE REVIEW

**Review by luytena — COMMENTED** [review]
Is name collision for components always an issue for ember-engines?

**Comment by anehx** [comment]
> Cd = Caluma Distribution?

Exactly, like `cf-` in `caluma-form` and `cfb-` in `caluma-form-builder`

**Comment by anehx** [comment]
> Is name collision for components always an issue for ember-engines?

It's always an issue for all kinds of addons, regardless if it's a normal addon or an engine. The component trees will always be merged with the host app which causes a collision if anything is named the same.

**Comment by luytena** [comment]
> > Is name collision for components always an issue for ember-engines?
> 
> It's always an issue for all kinds of addons, regardless if it's a normal addon or an engine. The component trees will always be merged with the host app which causes a collision if anything is named the same.

Oh, good to know :sweat_smile:

**Pull request merged**
