### PR TITLE
fix(ie11): fix checkboxes in IE11

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Comment by czosel** [comment]
Build seems to be failing ...

**Comment by anehx** [comment]
@czosel should be fixed

**Comment by anehx** [comment]
Actually I was thinking: do we really want to support IE11 in `ember-caluma`?

**Comment by czosel** [comment]
Since IE 11 is still officially supported, and caluma somewhat targets enterprise users, I think we have to support IE 11. Also, how would we have fixed this issue outside of the addon?

**Comment by anehx** [comment]
Well but it is also targeted for modern web applications.. However I agree that we should leave it *for now*. I just wanted to get that thought out.

The consumer can always overwrite the component...

**Pull request merged**
