### PR TITLE
chore(deps): update ember-uikit to v9.1.2

### PR DESCRIPTION
**Pull request by open-dynaMIX**

### CODE REVIEW

**Comment by open-dynaMIX** [comment]
@Yelinz The lock file diff is huge. Is that to be expected? I've edited the version in all `package.json` files and then ran `pnpm install`.

**Comment by Yelinz** [comment]
probably a differing pnpm version, try `corepack pnpm install` should choose the right version

**Comment by open-dynaMIX** [comment]
> probably a differing pnpm version, try `corepack pnpm install` should choose the right version

That was it, thanks :)

**Review by Yelinz — APPROVED** [review]

**Pull request merged**
