### PR TITLE
feat(form): show technical details of backend errors in UI

### PR DESCRIPTION
**Pull request by anehx**
error

### CODE REVIEW

**Comment by anehx** [comment]
BTW, for those who see this kind of stuff: the slight offset between the info and error icon was fixed after the demo was recorded :wink:

**Review by czosel — APPROVED** [review]
Nice!

**Comment by czosel** [comment]
Only idea, now that I also checked out the video: Should we add a message like "The answer could not be saved" before "Technical details"? Otherwise, people might be confused about what the "!" icon means exactly.

**Comment by anehx** [comment]
> Only idea, now that I also checked out the video: Should we add a message like "The answer could not be saved" before "Technical details"? Otherwise, people might be confused about what the "!" icon means exactly.

Good point. I added a message for the user and updated the GIF

**Review by czosel — APPROVED** [review]

**Pull request merged**
