### PR TITLE
feat(testing): allow inverting of filters

### PR DESCRIPTION
**Pull request by StephanH90**
## Description

Implements the `invert` option of the real caluma backend.

## Depedencies

No dependencies.

### CODE REVIEW

**Review by anehx — CHANGES_REQUESTED** [review]
Can you remove the existing implemenations of inversion? Otherwise those don't invert at all..

**Comment by StephanH90** [comment]
fixed the filters and added required tests.

**Review by anehx — APPROVED** [review]
Nice! :100:

**Pull request merged**
